services:
  spring:
    container_name: flint-spring
    depends_on:
      mysql:
        condition: service_healthy
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  mysql:
    image: mysql:8.0
    container_name: flint-mysql
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
