services:
  spring:
    container_name: flint-spring
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
